# Generated by Django 4.2.15 on 2024-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
