# Generated by Django 4.2.15 on 2024-09-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_featured_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'ordering': ['order'], 'verbose_name_plural': 'Featured'},
        ),
    ]
